### PR TITLE
KH-171:  Physical Exam questions changes in NCD Consultation form

### PR DESCRIPTION
**Pull request by kdaud**
Refer to [KH-171](https://issues.openmrs.org/browse/KH-171)

### CODE REVIEW

**Comment by kdaud** [comment]
@kazlaw for some reason that have not figured, all the answers in the Physical Exam section are not visible, could you be having an idea of what is happening?

**Review by kazlaw — COMMENTED** [review]
@kdaud from my test on Git Pod I noticed some answers are blank in the drop down lists for Left Foot and Right Foot Exams as well as that for Cardio Vascular System Exam.  Please Investigate

[KH-171-Missing-Concepts.webm](https://user-images.githubusercontent.com/36139599/233160062-ecafc628-92a1-4cde-9e56-8137bc7d6a4d.webm)

**Comment by kdaud** [comment]
@kazlaw, the issue is now fixed.

**Comment by kdaud** [comment]
Am encountering an error when submitting the form with user input.
[pysicalEx.webm](https://user-images.githubusercontent.com/38831673/233344279-a1f79ba2-8785-476c-bc21-42b5398ea7a4.webm)

**Pull request merged**
