### PR TITLE
KH-390: Added referral criterial under diagnosis section in NCD Screening form

### PR DESCRIPTION
**Pull request by kdaud**
Ticket → [KH-390](https://mekomsolutions.atlassian.net/browse/KH-390)

### CODE REVIEW

**Comment by kazlaw** [comment]
Hi @kdaud there was a typo I fixed [here](https://github.com/openmrs/ozone-distro-cambodia/pull/252/commits/84683a2f27455bf71ef0f27ebb72230a71ba02ec)

[Screencast from 28-11-23 19:35:20.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/36139599/892d1ee7-92c3-4e5f-90b5-430538196853)

**Comment by kazlaw** [comment]
I am going to utilize [this](https://docs.google.com/spreadsheets/d/13PHkzorfTmYRjuIJv3fCml3zBAuDba6Mgdpu4H7cAg8/edit?pli=1#gid=0&range=68:68) for the Khmer translation

**Review by kazlaw — COMMENTED** [review]
@kdaud please have look at this in the iniz logs

hyper-fail

**Comment by kdaud** [comment]
[NCDScreening.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/f6f4c13a-cba4-4a31-9665-4b7281967a74)

**Review by kazlaw — COMMENTED** [review]
Please have a look at this

referrrr

**Review by kazlaw — APPROVED** [review]
Looks good
looks okay

**Pull request merged**
