### PR TITLE
KH-444: Added new Cytology test for Cancer screening

### PR DESCRIPTION
**Pull request by vasharma05**
Link to ticket: https://mekomsolutions.atlassian.net/browse/KH-444

Working demo:

https://github.com/openmrs/ozone-distro-cambodia/assets/51502471/70387b62-2415-4a32-83ae-7064d7f345c9

### CODE REVIEW

**Comment by vasharma05** [comment]
@kazlaw @kdaud , please review.
Thanks!

**Comment by kazlaw** [comment]
Hi @vasharma05 the `cytology test` was added successfully but there are items missing as per the ticket description

**Comment by vasharma05** [comment]
Hi @kazlaw !
There are multiple tickets with the same description.
The items for HPV test is mentioned in the ticket [KH-435](https://mekomsolutions.atlassian.net/jira/software/c/projects/KH/boards/28?assignee=620394a2506317006b08378e&selectedIssue=KH-435) and the respective PR #280 .
Thanks!

**Review by kazlaw — APPROVED** [review]
Looks good 

image


[Screencast from 08-01-24 17:01:11.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/36139599/af463ea4-267b-4c4b-8415-0426652c11b2)

**Pull request merged**
