### PR TITLE
KH-426: Replace Ozone with MOH logo

### PR DESCRIPTION
**Pull request by kazlaw**
Link to ticket here --> https://mekomsolutions.atlassian.net/browse/KH-460

### CODE REVIEW

**Comment by rbuisson** [comment]
@kazlaw , please also make sure to exclude the logos inherited from Ozone using the Maven exclusions:
https://github.com/openmrs/ozone-distro-cambodia/blob/11b2b295154fed8ea6cf4fc24e2e173a37d02a70/base/pom.xml#L89-L98

**Comment by kazlaw** [comment]
> @kazlaw , please also make sure to exclude the logos inherited from Ozone using the Maven exclusions:
> 
> https://github.com/openmrs/ozone-distro-cambodia/blob/11b2b295154fed8ea6cf4fc24e2e173a37d02a70/base/pom.xml#L89-L98

Noted, thanks

**Comment by kazlaw** [comment]
> @kazlaw , please also make sure to exclude the logos inherited from Ozone using the Maven exclusions:
> 
> https://github.com/openmrs/ozone-distro-cambodia/blob/11b2b295154fed8ea6cf4fc24e2e173a37d02a70/base/pom.xml#L89-L98

Noted, thanks

**Comment by vasharma05** [comment]
I am not able to see the changes reflecting on Gitpod.

**Comment by kazlaw** [comment]
Changes tested as below

[Screencast from 10-01-24 22:59:01.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/36139599/91fa7e6f-c139-4ffb-a8bb-187422b9a6ac)

**Pull request merged**
