### PR TITLE
KH-262: Add answers to other health conditions in NCD Screening form

### PR DESCRIPTION
**Pull request by kdaud**
Ticket - [KH-262](https://mekomsolutions.atlassian.net/browse/KH-262)

### CODE REVIEW

**Comment by kazlaw** [comment]
@kdaud please resolve the conflicting files

**Comment by kdaud** [comment]
> @kdaud please resolve the conflicting files

Done!

**Comment by kazlaw** [comment]
@kdaud  since the current set of changes affects similar files we have a conflict again. Kindly resolve

**Comment by kazlaw** [comment]
@kdaud please a look

**Comment by kdaud** [comment]
> @kdaud please a look

Done!

**Review by kazlaw — APPROVED** [review]
Looks good

**Pull request merged**
