### PR TITLE
KH-442: Updated the fields for breast cancer in Cervical Cancer Screening

### PR DESCRIPTION
**Pull request by vasharma05**
Link to ticket: https://mekomsolutions.atlassian.net/browse/KH-442

1. Have you been educated on self-breast checking? តើបានអប់រំ និងបង្រៀនស្ត្រីអំពីការពិនិត្យដោះដោយខ្លួនឯងដែរឬទេ? Answers:
Yes (បាន) 
No (មិនបាន) 

2. Sign of breast (សញ្ញាណបញ្ហារបស់ដោះ) Answers:
Normal (ធម្មតា) 
Abscesses (បូស - រលាក) 
Tumor (ដុំសាច់) 
Suspected breast cancer (សង្ស័យមហារីកដោះ) 
Other

3. Referral field

4. Breast cancer reason for Referral (មូលហេតុបញ្ជូន) 
+Tumor (ដុំសាច់)
+Suspected breast cancer

https://github.com/openmrs/ozone-distro-cambodia/assets/51502471/9aec947e-3e20-4537-8c7c-432b45db746e

image

### CODE REVIEW

**Comment by vasharma05** [comment]
Hi @kazlaw @kdaud , please review this PR.
Thanks!

**Comment by kazlaw** [comment]
Hi @vasharma05 please resolve the conflicts here

**Comment by vasharma05** [comment]
image

image

**Review by kazlaw — APPROVED** [review]
Looks good

**Pull request merged**
