### PR TITLE
KH-434: Added drug 'Simvastatin 10mg' in medication of treatment plan

### PR DESCRIPTION
**Pull request by kdaud**
Ticket → [KH-434](https://mekomsolutions.atlassian.net/browse/KH-434)

### CODE REVIEW

**Comment by vasharma05** [comment]
Is this PR dependent on #268 ?

**Comment by vasharma05** [comment]
Unable to test this PR, getting  CSRF issue when creating provider account.
Thanks!

**Comment by kdaud** [comment]
> Is this PR dependent on https://github.com/openmrs/ozone-distro-cambodia/pull/268

 yes.

**Comment by kazlaw** [comment]
Hi @kdaud please resolve the conflicts

**Review by kazlaw — APPROVED** [review]
Looks good

**Pull request merged**
