### PR TITLE
KH-116: Split concepts, and provide responses for ketone concept

### PR DESCRIPTION
**Pull request by kdaud**
Refer to the Jira [comment](https://issues.openmrs.org/browse/KH-116?focusedCommentId=288794&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-288794)

### CODE REVIEW

**Review by kazlaw — COMMENTED** [review]
@kdaud, had you tested this?

**Comment by kdaud** [comment]
See the UX
[screening.webm](https://user-images.githubusercontent.com/38831673/233336852-a5a506a1-202c-4ce8-be0d-6b942c4fb337.webm)

**Comment by kazlaw** [comment]
[Split-ketone.webm](https://user-images.githubusercontent.com/36139599/234485321-bc1fbc48-7ffa-40bf-bf32-4fb9e67ce4d6.webm)
 
 Looks like it matches the acceptance criteria

**Comment by rbuisson** [comment]
@kazlaw , so is that approved?

**Comment by kazlaw** [comment]
Yes @rbuisson , I tried to find  where to approve and I wasn't able to

**Review by kazlaw — APPROVED** [review]
[Split-ketone.webm](https://user-images.githubusercontent.com/36139599/234514350-2a803b39-d27f-4bb4-94a6-b511cda04ffa.webm)

This is okay for merge @rbuisson

**Pull request merged**
