### PR TITLE
KH-355: Display Referral Centers if VIA test results or Breast Cancer Exams are abnormal

### PR DESCRIPTION
**Pull request by kazlaw**
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-355)

### CODE REVIEW

**Comment by kazlaw** [comment]
@kdaud please have a look

[Screencast from 24-10-23 21:14:44.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/36139599/0194b81d-488a-4a36-a306-9a13e719710e)

**Comment by kdaud** [comment]
@kazlaw do we intend to display the referral centers when one of the conditions (either VIA test result or Breast Cancer Exams) is abnormal and the other is normal?

**Comment by kazlaw** [comment]
Yes that's what the ticket says

**Comment by kdaud** [comment]
I've tested out the changes and the referral center displays only when both conditions are abnormal.

**Comment by kazlaw** [comment]
@kdaud this is working well now

[Screencast from 28-11-23 18:32:48.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/36139599/c19f8983-5dbb-4161-8b6c-ba1c1f6db2c3)

**Pull request merged**
