### PR TITLE
KH-392: Override Common Reports Module with version 1.4.0

### PR DESCRIPTION
**Pull request by Ruhanga**
TIcket: https://mekomsolutions.atlassian.net/browse/KH-392

### CODE REVIEW

**Review by rbuisson — CHANGES_REQUESTED** [review]
We end up with both Common Reports versions (1.3.0 from Ozone and 1.4.0 from Oz Kh).

You should add the line below, under [this line](https://github.com/openmrs/ozone-distro-cambodia/blob/cd2617522a20750a8ad66e25ff81f8c13e8259a8/base/pom.xml#L99), to the current Ozone exclusions in the `base/pom.xml` file, :

```xml
<!-- Excluding the Common Reports OpenMRS module inherited from Ozone -->
<exclude>distro/binaries/openmrs/modules/commonreports-1.3.0.omod</exclude>
```

**Comment by rbuisson** [comment]
@Ruhanga : this is what the screen looks like:

Screenshot 2024-01-24 at 17 59 35

What should be done to provide the correct label?

**Comment by Ruhanga** [comment]
> What should be done to provide the correct label?

I will update Ozone KH config with the necessary message properties.

**Comment by Ruhanga** [comment]
@rbuisson I've republished Common Reports and we should be good to go now.

**Comment by rbuisson** [comment]
> we don't need to add that line as OpenMRS core removes it for us in favour of the 1.4.0 version.

Well the distro itself ends up containing 2 versions. I would suggest to still exclude it so to keep things clear and clean.
Though maybe I would even not specify the version and exclude `commonreports-*.omod`.

**Comment by Ruhanga** [comment]
@rbuisson, this should be ok now?

**Comment by rbuisson** [comment]
@Ruhanga  please see the actual snippet I've suggested.
Add this as well:
```
<!-- Excluding the Common Reports OpenMRS module inherited from Ozone -->
```

**Review by rbuisson — APPROVED** [review]

**Pull request merged**
