### PR TITLE
KH-73: Add Education entry at registration

### PR DESCRIPTION
**Pull request by kazlaw**
https://issues.openmrs.org/browse/KH-73

### CODE REVIEW

**Comment by kazlaw** [comment]
[Education Added with en-kh.webm](https://user-images.githubusercontent.com/36139599/221624312-3069ac80-da7e-498f-afc2-5cd5dd3b87ae.webm)

**Comment by rbuisson** [comment]
Thanks @kazlaw . This branch has conflicts though. Is it possible to resolve them first?

**Comment by kazlaw** [comment]
Sure @rbuisso,let me look into this

**Comment by kazlaw** [comment]
@rbuisson  a commit has been made [here](https://github.com/openmrs/ozone-distro-cambodia/pull/12/commits/bd21869418775d7b09258c925bac41a262239e94)

**Pull request closed without merging**
