### PR TITLE
KH-317: Change '6 months - 1 year' to '1 year' for Cervical Screening Follow up question

### PR DESCRIPTION
**Pull request by kazlaw**
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-317)

### CODE REVIEW

**Comment by kazlaw** [comment]
@kdaud please to have a look

[Screencast from 21-08-23 20:56:47.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/36139599/566f00c2-989b-4947-aba6-36cb2ea49561)

**Review by kdaud — APPROVED** [review]
[FollowUp.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/8db24905-4747-499e-b281-a4fba8563391)

**Comment by kdaud** [comment]
@kazlaw, could you confirm the translation for `1 year` then we can have this merged?

**Comment by kazlaw** [comment]
> @kazlaw, could you confirm the translation for `1 year` then we can have this merged?

A Slack conversation has been started [here](https://openmrs.slack.com/archives/C03ESJABQKY/p1692859964020689)

**Review by kdaud — APPROVED** [review]

**Pull request merged**
