### PR TITLE
KH-428: Override Khmer translation for 'markDeceased'

### PR DESCRIPTION
**Pull request by kdaud**
Ticket → [KH-428](https://mekomsolutions.atlassian.net/browse/KH-428)

### CODE REVIEW

**Comment by kazlaw** [comment]
Hi @kdaud kindly attach a video here

**Comment by kazlaw** [comment]
Hi @kdaud when you get a chance please resolve these conflicts and we test this. Thanks

**Review by kazlaw — COMMENTED** [review]
Kindly resolve the conflicts.

**Comment by kdaud** [comment]
[MarkDeceasedPatient.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/6d8d2644-7618-4b7e-8a85-ad033bdd0408)

**Review by kazlaw — COMMENTED** [review]
Initialiser logs look good as below

**Review by kazlaw — APPROVED** [review]

**Pull request merged**
