### PR TITLE
KH-253: Add a question 'Has a referral letter ?' in start visit page

### PR DESCRIPTION
**Pull request by kazlaw**
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-253)

### CODE REVIEW

**Comment by kazlaw** [comment]
@kdaud kindly have a look when you get a chance

KH-253
KH--253-1

**Comment by kdaud** [comment]
@kazlaw, there are some conflicting files that need to be resolved.

**Comment by kazlaw** [comment]
@kdaud this has been resolved

**Comment by kazlaw** [comment]
Please have another look

**Review by kdaud — APPROVED** [review]

**Pull request merged**
