### PR TITLE
KH-222: Better consistency in form naming

### PR DESCRIPTION
**Pull request by kdaud**
Ticket → [KH-222](https://mekomsolutions.atlassian.net/browse/KH-222)

### CODE REVIEW

**Comment by kazlaw** [comment]
@kdaud this has conflicts kindly address them

**Comment by kazlaw** [comment]
Form is not loading
form-errors-11

**Comment by kdaud** [comment]
@kazlaw the form is loading well and able submit user input.

[NCDScreening.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/f2abc195-fa5d-4642-80b4-5e5dd83246d3)

**Review by kazlaw — APPROVED** [review]
Looks good

[Screencast from 08-09-23 16:41:45.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/36139599/a4e5483c-419c-47af-b4b1-7914285eb0c8)

**Comment by kdaud** [comment]
@kazlaw I reverted the PR because the form was being duplicated on the dev server. Unfortunately I'm not able to reproduce the issue locally and also via Gitpod.

**Pull request merged**
