### PR TITLE
KH-116: Modify responses for ketone under lipids section

### PR DESCRIPTION
**Pull request by kdaud**
Refer to the Jira [comment](https://issues.openmrs.org/browse/KH-116?focusedCommentId=289032&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-289032)

[Ketone.webm](https://user-images.githubusercontent.com/38831673/234740891-2365b945-816d-43c0-8b7e-1bdfbb0ecbe4.webm)

### CODE REVIEW

**Review by kazlaw — APPROVED** [review]
This works as desired from the test here.

[Ketone fixed.webm](https://user-images.githubusercontent.com/36139599/234795538-14068c27-ad4b-4ae4-940f-ac3c138affed.webm)

**Review by rbuisson — APPROVED** [review]

**Comment by rbuisson** [comment]
@kazlaw @kdaud , from conversation with Khaled and as written on the ticket, we need to have the fix in the NCD Consultation form (Medical Assessment section)

**Review by kazlaw — COMMENTED** [review]
@kdaud, Please make chages to the `Ketone` question in NCD Consultation form to be like the one in the HC -Screening form . Kindly review the comments from Khaled h[ere](https://issues.openmrs.org/browse/KH-116)

**Review by kazlaw — APPROVED** [review]
This works as expected
[Gitpod-fix-KH-116.webm](https://user-images.githubusercontent.com/36139599/235073327-cd05ac0b-97bc-41be-b5d1-25a5f19f7fb8.webm)

**Pull request merged**
