### PR TITLE
KH-93: Fix Address levels not correctly translated

### PR DESCRIPTION
**Pull request by kazlaw**
https://issues.openmrs.org/browse/KH-93

### CODE REVIEW

**Comment by rbuisson** [comment]
Looks good. Thanks @kazlaw .

**Comment by rbuisson** [comment]
@kazlaw, at the moment, we are loading the address template via the global property `layout.address.format` as you've updated.

However, this template should be in theory loaded via the _Address Configuration_ of the Address Hierachy module.
This is done here: https://github.com/openmrs/ozone-distro-cambodia/blob/main/configs/openmrs_config/addresshierarchy/addressConfiguration.xml

But there is currently a regression that makes the Address Configuration not correctly loaded. See the existing ticket https://issues.openmrs.org/projects/ADDR/issues/ADDR-124

So... it would actually be great if you could try and confirm that indeed there is a bug there. And if so, report in the linked ticket.
In the mean time, could you make sure to also update this Address Config XML file in the config with your new changes so to keep it accurate.

**Comment by kazlaw** [comment]
Noted @rbuisson , let me make changes and do tests then report accordingly

**Comment by kazlaw** [comment]
@rbuisson  a commit has been made [here](https://github.com/openmrs/ozone-distro-cambodia/pull/15/commits/0803e6314817dc809eb3f39d510e8e86cf9f9afe)

**Pull request merged**
